obj-$(CONFIG_CRYPTO_DEV_SEMIDRIVE) += semidrive-crypto-dev.o
semidrive-crypto-dev-objs:= sd_rsa.o sd_ecdsa.o sx_ecdsa.o sx_rsa_pad.o \
							sx_rsa.o sx_prime.o sx_trng.o sx_sm2.o sx_pke_conf.o \
							sx_pke_funcs.o sx_dma.o sram_conf.o ce.o sx_ecc_keygen.o \
							sx_ecc.o sx_hash.o semidrive-crypto.o crypto-process.o \
							cryptlib.o zc.o sdrv-hash.o sdrv-cipher.o sx_cipher.o \
							sdrv-rsa.o sx_ecc_keygen.o

