/**
 * Semidrive SID header file
 *
 * Copyright (C) 2019, Semidrive Semiconductor
 *
 * All rights reserved.
 */

/**
 * This file is automatically generated by Semidrive.
 */

#ifndef DT_BINDINGS_MEMORY_SDRV_SID_H
#define DT_BINDINGS_MEMORY_SDRV_SID_H

/* =========================
 *        Stream IDs
 * =========================
 */
#define SDRV_SID_SAF_PLATFORM	0
#define SDRV_SID_SEC_PLATFORM	1
#define SDRV_SID_MP_PLATFORM	2
#define SDRV_SID_AP1			3

#define SDRV_SID_VDSP			5

#define SDRV_SID_TCU			7
#define SDRV_SID_DMA1			8
#define SDRV_SID_DMA2			9
#define SDRV_SID_DMA3			10
#define SDRV_SID_DMA4			11
#define SDRV_SID_DMA5			12
#define SDRV_SID_DMA6			13
#define SDRV_SID_DMA7			14
#define SDRV_SID_DMA8			15
#define SDRV_SID_CSI1			16
#define SDRV_SID_CSI2			17
#define SDRV_SID_CSI3			18
#define SDRV_SID_DC1			19
#define SDRV_SID_DC2			20
#define SDRV_SID_DC3			21
#define SDRV_SID_DC4			22
#define SDRV_SID_DP1			23
#define SDRV_SID_DP2			24
#define SDRV_SID_DP3			25
#define SDRV_SID_DC5			26
#define SDRV_SID_G2D1			27
#define SDRV_SID_G2D2			28
#define SDRV_SID_VPU1			29
#define SDRV_SID_VPU2			30
#define SDRV_SID_MJPEG			31
#define SDRV_SID_MSHC1			32
#define SDRV_SID_MSHC2			33
#define SDRV_SID_MSHC3			34
#define SDRV_SID_MSHC4			35
#define SDRV_SID_ETH1			36
#define SDRV_SID_ETH2			37
#define SDRV_SID_USB1			38
#define SDRV_SID_USB2			39

#define SDRV_SID_CE1			47
#define SDRV_SID_CE2_VCE1		48
#define SDRV_SID_CE2_VCE2		49
#define SDRV_SID_CE2_VCE3		50
#define SDRV_SID_CE2_VCE4		51
#define SDRV_SID_CE2_VCE5		52
#define SDRV_SID_CE2_VCE6		53
#define SDRV_SID_CE2_VCE7		54
#define SDRV_SID_CE2_VCE8		55
#define SDRV_SID_GPU1_OS1		56
#define SDRV_SID_GPU1_OS2		57
#define SDRV_SID_GPU1_OS3		58
#define SDRV_SID_GPU1_OS4		59
#define SDRV_SID_GPU1_OS5		60
#define SDRV_SID_GPU1_OS6		61
#define SDRV_SID_GPU1_OS7		62
#define SDRV_SID_GPU1_OS8		63
#define SDRV_SID_GPU2_OS1		64
#define SDRV_SID_GPU2_OS2		65
#define SDRV_SID_GPU2_OS3		66
#define SDRV_SID_GPU2_OS4		67
#define SDRV_SID_GPU2_OS5		68
#define SDRV_SID_GPU2_OS6		69
#define SDRV_SID_GPU2_OS7		70
#define SDRV_SID_GPU2_OS8		71
#define SDRV_SID_PTB			72
#define SDRV_SID_CSSYS			73

#define SDRV_SID_PCIE1_0		80
#define SDRV_SID_PCIE1_1		81
#define SDRV_SID_PCIE1_2		82
#define SDRV_SID_PCIE1_3		83
#define SDRV_SID_PCIE1_4		84
#define SDRV_SID_PCIE1_5		85
#define SDRV_SID_PCIE1_6		86
#define SDRV_SID_PCIE1_7		87
#define SDRV_SID_PCIE1_8		88
#define SDRV_SID_PCIE1_9		89
#define SDRV_SID_PCIE1_10		90
#define SDRV_SID_PCIE1_11		91
#define SDRV_SID_PCIE1_12		92
#define SDRV_SID_PCIE1_13		93
#define SDRV_SID_PCIE1_14		94
#define SDRV_SID_PCIE1_15		95
#define SDRV_SID_PCIE2_0		96
#define SDRV_SID_PCIE2_1		97
#define SDRV_SID_PCIE2_2		98
#define SDRV_SID_PCIE2_3		99
#define SDRV_SID_PCIE2_4		100
#define SDRV_SID_PCIE2_5		101
#define SDRV_SID_PCIE2_6		102
#define SDRV_SID_PCIE2_7		103

#endif
