/**
 * Semidrive ION header file
 *
 * Copyright (C) 2019, Semidrive Semiconductor
 *
 * All rights reserved.
 */

/**
 * This file is automatically generated by Semidrive.
 */

#ifndef DT_BINDINGS_MEMORY_SDRV_ION_H
#define DT_BINDINGS_MEMORY_SDRV_ION_H

/* ==========================
 *   Particular Heap Types
 * ==========================
 */
#define	ION_HEAP_NAME_CARVEOUT "carveout"

#endif
