/*
 * sdrv-unilink-x9.h
 *
 * Copyright(c) 2022 Semidrive
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 *
 */

#ifndef __DT_BINDINGS_SDRV_ULINK_X9U_H
#define __DT_BINDINGS_SDRV_ULINK_X9U_H

#ifndef SERVICES_MEMBASE
#error "undefined macro SERVICES_MEMBASE"
#endif

#define round_up(a,b) (((a - 1) | (b - 1)) + 1)
#define LINK_SIZE 0x4000000
#define LINK_DDR_BASE (round_up(SERVICES_MEMBASE, LINK_SIZE))


#define UNILINK_TX_BASE_R 0x18000000
#define UNILINK_RX_BASE_R (LINK_DDR_BASE) //0x78000000
#define UNILINK_TX_BASE_L (UNILINK_RX_BASE_R+LINK_SIZE)//0x7c000000
#define UNILINK_RX_BASE_L (UNILINK_RX_BASE_R+LINK_SIZE) //0x7c000000

#define SAF_TO_SAF_R 0x400000
#define SAF_TO_AP1_R 0x800000
#define SAF_TO_AP2_R 0xc00000
#define AP1_TO_SAF_R 0x1400000
#define AP1_TO_AP1_R 0x1800000
#define AP1_TO_AP2_R 0x1c00000
#define AP2_TO_SAF_R 0x2400000
#define AP2_TO_AP1_R 0x2800000
#define AP2_TO_AP2_R 0x2c00000

#define SAF_TO_AP1 0x0
#define SAF_TO_AP2 0x200000
#define AP1_TO_SAF 0x400000
#define AP1_TO_AP2 0x800000
#define AP2_TO_SAF 0xa00000
#define AP2_TO_AP1 0xc00000
/*AP1*/
#define UNILINK_TX_AP1_TO_SAF_L (UNILINK_TX_BASE_L + AP1_TO_SAF)
#define UNILINK_RX_AP1_TO_SAF_L (UNILINK_RX_BASE_L + SAF_TO_AP1)
#define UNILINK_TX_AP1_TO_AP2_L (UNILINK_TX_BASE_L + AP1_TO_AP2)
#define UNILINK_RX_AP1_TO_AP2_L (UNILINK_RX_BASE_L + AP2_TO_AP1)

#define UNILINK_TX_AP1_TO_SAF_R (UNILINK_TX_BASE_R + AP1_TO_SAF_R)
#define UNILINK_RX_AP1_TO_SAF_R (UNILINK_RX_BASE_R + SAF_TO_AP1_R)
#define UNILINK_TX_AP1_TO_AP1_R (UNILINK_TX_BASE_R + AP1_TO_AP1_R)
#define UNILINK_RX_AP1_TO_AP1_R (UNILINK_RX_BASE_R + AP1_TO_AP1_R)
#define UNILINK_TX_AP1_TO_AP2_R (UNILINK_TX_BASE_R + AP1_TO_AP2_R)
#define UNILINK_RX_AP1_TO_AP2_R (UNILINK_RX_BASE_R + AP2_TO_AP1_R)
/*AP2*/
#define UNILINK_TX_AP2_TO_SAF_L (UNILINK_TX_BASE_L + AP2_TO_SAF)
#define UNILINK_RX_AP2_TO_SAF_L (UNILINK_RX_BASE_L + SAF_TO_AP2)
#define UNILINK_TX_AP2_TO_AP1_L (UNILINK_TX_BASE_L + AP2_TO_AP1)
#define UNILINK_RX_AP2_TO_AP1_L (UNILINK_RX_BASE_L + AP1_TO_AP2)

#define UNILINK_TX_AP2_TO_SAF_R (UNILINK_TX_BASE_R + AP2_TO_SAF_R)
#define UNILINK_RX_AP2_TO_SAF_R (UNILINK_RX_BASE_R + SAF_TO_AP2_R)
#define UNILINK_TX_AP2_TO_AP1_R (UNILINK_TX_BASE_R + AP2_TO_AP1_R)
#define UNILINK_RX_AP2_TO_AP1_R (UNILINK_RX_BASE_R + AP1_TO_AP2_R)
#define UNILINK_TX_AP2_TO_AP2_R (UNILINK_TX_BASE_R + AP2_TO_AP2_R)
#define UNILINK_RX_AP2_TO_AP2_R (UNILINK_RX_BASE_R + AP2_TO_AP2_R)

#endif /* __DT_BINDINGS_SDRV_ULINK_X9_H */
