# Overlays for semidrive platform

dtbo-$(CONFIG_ARCH_SEMIDRIVE) += \
	audio-ak4556-enable.dtbo \
	audio-tlv320-enable.dtbo \
	audio-ak4556-disable.dtbo \
	audio-tlv320-disable.dtbo \
	audio-ak7738.dtbo \
	audio-ak7738-ms.dtbo \
	audio-tlv320-ms.dtbo
always          := $(dtbo-y)
clean-files     := *.dtbo
