# Semidrive soc drivers
# ctreat by chentinaming
# data:2019/7/04

subdir-ccflags-y += -I$(srctree)/drivers/media/platform/semidrive/include \
	-I$(srctree)/drivers/media/platform/semidrive/vpuvirtio
obj-$(CONFIG_SEMIDRIVE_VPU_CODA988)  += vpucoda988/ vpuvirtio/
obj-$(CONFIG_SEMIDRIVE_VPU_WAVE412)  += vpuwave412/ vpuvirtio/
obj-$(CONFIG_SEMIDRIVE_JPU_CODAJ12)  += jpucodaj12/
