ccflags-y += -Idrivers/media/platform/sdrv-cam-v2/
ccflags-y += -Idrivers/media/platform/sdrv-cam-v2/common
ccflags-y += -Idrivers/media/platform/sdrv-cam-v2/mipicsi
ccflags-y += -Idrivers/media/platform/sdrv-cam-v2/csi-controller
ccflags-y += -Idrivers/media/platform/sdrv-cam-v2/external/sensor
ccflags-y += -Idrivers/media/platform/sdrv-cam-v2/external/serdes

ccflags-y += -D__LINUX__

obj-$(CONFIG_VIDEO_SEMIDRIVE_V2) += mipicsi-ip.o
obj-$(CONFIG_VIDEO_SEMIDRIVE_V2) += mipicsi-os.o
