#
# Makefile for the semidrive cpu budget cooling drivers.
#
obj-$(CONFIG_SEMIDRIVE_CPUFREQ_COOLING) += semidrive_cpufreq_cooling.o
obj-$(CONFIG_SEMIDRIVE_CPUCORE_COOLING) += semidrive_cpucore_cooling.o
