# SPDX-License-Identifier: GPL-2.0
# Semidrive pin control drivers
obj-$(CONFIG_PINCTRL_SEMIDRIVE)	+= pinctrl-common.o
obj-$(CONFIG_PINCTRL_SD_MEMMAP)+= pinctrl-memmap.o
obj-$(CONFIG_PINCTRL_SDX9)	+= pinctrl-x9.o
