/*
* Copyright (c) 2019 Semidrive Semiconductor.
* All rights reserved.
*
*/

#include <linux/err.h>
#include <linux/init.h>
#include <linux/io.h>
#include <linux/of.h>
#include <linux/of_device.h>
#include <linux/pinctrl/pinctrl.h>

#include "pinctrl-common.h"

/*
* should in keep with identify with pins-sdx9.h
*/
enum kunlun_pads {
	X9_PINCTRL_GPIO_C0 = 0,
    X9_PINCTRL_GPIO_C1 = 1,
    X9_PINCTRL_GPIO_C2 = 2,
    X9_PINCTRL_GPIO_C3 = 3,
    X9_PINCTRL_GPIO_C4 = 4,
    X9_PINCTRL_GPIO_C5 = 5,
    X9_PINCTRL_GPIO_C6 = 6,
    X9_PINCTRL_GPIO_C7 = 7,
    X9_PINCTRL_GPIO_C8 = 8,
    X9_PINCTRL_GPIO_C9 = 9,
    X9_PINCTRL_GPIO_C10 = 10,
    X9_PINCTRL_GPIO_C11 = 11,
    X9_PINCTRL_GPIO_C12 = 12,
    X9_PINCTRL_GPIO_C13 = 13,
    X9_PINCTRL_GPIO_C14 = 14,
    X9_PINCTRL_GPIO_C15 = 15,
    X9_PINCTRL_GPIO_D0 = 16,
    X9_PINCTRL_GPIO_D1 = 17,
    X9_PINCTRL_GPIO_D2 = 18,
    X9_PINCTRL_GPIO_D3 = 19,
    X9_PINCTRL_GPIO_D4 = 20,
    X9_PINCTRL_GPIO_D5 = 21,
    X9_PINCTRL_GPIO_D6 = 22,
    X9_PINCTRL_GPIO_D7 = 23,
    X9_PINCTRL_GPIO_D8 = 24,
    X9_PINCTRL_GPIO_D9 = 25,
    X9_PINCTRL_GPIO_D10 = 26,
    X9_PINCTRL_GPIO_D11 = 27,
    X9_PINCTRL_GPIO_D12 = 28,
    X9_PINCTRL_GPIO_D13 = 29,
    X9_PINCTRL_GPIO_D14 = 30,
    X9_PINCTRL_GPIO_D15 = 31,
	X9_PINCTRL_OSPI2_SCLK = 32,
    X9_PINCTRL_OSPI2_SS0 = 33,
    X9_PINCTRL_OSPI2_DATA0 = 34,
    X9_PINCTRL_OSPI2_DATA1 = 35,
    X9_PINCTRL_OSPI2_DATA2 = 36,
    X9_PINCTRL_OSPI2_DATA3 = 37,
    X9_PINCTRL_OSPI2_DATA4 = 38,
    X9_PINCTRL_OSPI2_DATA5 = 39,
    X9_PINCTRL_OSPI2_DATA6 = 40,
    X9_PINCTRL_OSPI2_DATA7 = 41,
    X9_PINCTRL_OSPI2_DQS = 42,
    X9_PINCTRL_OSPI2_SS1 = 43,
    X9_PINCTRL_RGMII2_TXC = 44,
    X9_PINCTRL_RGMII2_TXD0 = 45,
    X9_PINCTRL_RGMII2_TXD1 = 46,
    X9_PINCTRL_RGMII2_TXD2 = 47,
    X9_PINCTRL_RGMII2_TXD3 = 48,
    X9_PINCTRL_RGMII2_TX_CTL = 49,
    X9_PINCTRL_RGMII2_RXC = 50,
    X9_PINCTRL_RGMII2_RXD0 = 51,
    X9_PINCTRL_RGMII2_RXD1 = 52,
    X9_PINCTRL_RGMII2_RXD2 = 53,
    X9_PINCTRL_RGMII2_RXD3 = 54,
    X9_PINCTRL_RGMII2_RX_CTL = 55,
    X9_PINCTRL_I2S_SC3_SCK = 56,
    X9_PINCTRL_I2S_SC3_WS = 57,
    X9_PINCTRL_I2S_SC3_SD = 58,
    X9_PINCTRL_I2S_SC4_SCK = 59,
    X9_PINCTRL_I2S_SC4_WS = 60,
    X9_PINCTRL_I2S_SC4_SD = 61,
    X9_PINCTRL_I2S_SC5_SCK = 62,
    X9_PINCTRL_I2S_SC5_WS = 63,
    X9_PINCTRL_I2S_SC5_SD = 64,
    X9_PINCTRL_I2S_SC6_SCK = 65,
    X9_PINCTRL_I2S_SC6_WS = 66,
    X9_PINCTRL_I2S_SC6_SD = 67,
    X9_PINCTRL_I2S_SC7_SCK = 68,
    X9_PINCTRL_I2S_SC7_WS = 69,
    X9_PINCTRL_I2S_SC7_SD = 70,
    X9_PINCTRL_I2S_SC8_SCK = 71,
    X9_PINCTRL_I2S_SC8_WS = 72,
    X9_PINCTRL_I2S_SC8_SD = 73,
    X9_PINCTRL_I2S_MC_SCK = 74,
    X9_PINCTRL_I2S_MC_WS = 75,
    X9_PINCTRL_I2S_MC_SD0 = 76,
    X9_PINCTRL_I2S_MC_SD1 = 77,
    X9_PINCTRL_I2S_MC_SD2 = 78,
    X9_PINCTRL_I2S_MC_SD3 = 79,
    X9_PINCTRL_I2S_MC_SD4 = 80,
    X9_PINCTRL_I2S_MC_SD5 = 81,
    X9_PINCTRL_I2S_MC_SD6 = 82,
    X9_PINCTRL_I2S_MC_SD7 = 83,
    X9_PINCTRL_EMMC1_CLK = 84,
    X9_PINCTRL_EMMC1_CMD = 85,
    X9_PINCTRL_EMMC1_DATA0 = 86,
    X9_PINCTRL_EMMC1_DATA1 = 87,
    X9_PINCTRL_EMMC1_DATA2 = 88,
    X9_PINCTRL_EMMC1_DATA3 = 89,
    X9_PINCTRL_EMMC1_DATA4 = 90,
    X9_PINCTRL_EMMC1_DATA5 = 91,
    X9_PINCTRL_EMMC1_DATA6 = 92,
    X9_PINCTRL_EMMC1_DATA7 = 93,
    X9_PINCTRL_EMMC1_STROBE = 94,
    X9_PINCTRL_EMMC1_RESET_N = 95,
    X9_PINCTRL_EMMC2_CLK = 96,
    X9_PINCTRL_EMMC2_CMD = 97,
    X9_PINCTRL_EMMC2_DATA0 = 98,
    X9_PINCTRL_EMMC2_DATA1 = 99,
    X9_PINCTRL_EMMC2_DATA2 = 100,
    X9_PINCTRL_EMMC2_DATA3 = 101,
    X9_PINCTRL_EMMC2_DATA4 = 102,
    X9_PINCTRL_EMMC2_DATA5 = 103,
    X9_PINCTRL_EMMC2_DATA6 = 104,
    X9_PINCTRL_EMMC2_DATA7 = 105,
    X9_PINCTRL_EMMC2_STROBE = 106,
    X9_PINCTRL_EMMC2_RESET_N = 107,
};

/* Pad names for the pinmux subsystem */
static const struct pinctrl_pin_desc kunlun_pinctrl_pads[] = {
    SD_PINCTRL_PIN(X9_PINCTRL_GPIO_C0),
    SD_PINCTRL_PIN(X9_PINCTRL_GPIO_C1),
    SD_PINCTRL_PIN(X9_PINCTRL_GPIO_C2),
    SD_PINCTRL_PIN(X9_PINCTRL_GPIO_C3),
    SD_PINCTRL_PIN(X9_PINCTRL_GPIO_C4),
    SD_PINCTRL_PIN(X9_PINCTRL_GPIO_C5),
    SD_PINCTRL_PIN(X9_PINCTRL_GPIO_C6),
    SD_PINCTRL_PIN(X9_PINCTRL_GPIO_C7),
    SD_PINCTRL_PIN(X9_PINCTRL_GPIO_C8),
    SD_PINCTRL_PIN(X9_PINCTRL_GPIO_C9),
    SD_PINCTRL_PIN(X9_PINCTRL_GPIO_C10),
    SD_PINCTRL_PIN(X9_PINCTRL_GPIO_C11),
    SD_PINCTRL_PIN(X9_PINCTRL_GPIO_C12),
    SD_PINCTRL_PIN(X9_PINCTRL_GPIO_C13),
    SD_PINCTRL_PIN(X9_PINCTRL_GPIO_C14),
    SD_PINCTRL_PIN(X9_PINCTRL_GPIO_C15),
    SD_PINCTRL_PIN(X9_PINCTRL_GPIO_D0),
    SD_PINCTRL_PIN(X9_PINCTRL_GPIO_D1),
    SD_PINCTRL_PIN(X9_PINCTRL_GPIO_D2),
    SD_PINCTRL_PIN(X9_PINCTRL_GPIO_D3),
    SD_PINCTRL_PIN(X9_PINCTRL_GPIO_D4),
    SD_PINCTRL_PIN(X9_PINCTRL_GPIO_D5),
    SD_PINCTRL_PIN(X9_PINCTRL_GPIO_D6),
    SD_PINCTRL_PIN(X9_PINCTRL_GPIO_D7),
    SD_PINCTRL_PIN(X9_PINCTRL_GPIO_D8),
    SD_PINCTRL_PIN(X9_PINCTRL_GPIO_D9),
    SD_PINCTRL_PIN(X9_PINCTRL_GPIO_D10),
    SD_PINCTRL_PIN(X9_PINCTRL_GPIO_D11),
    SD_PINCTRL_PIN(X9_PINCTRL_GPIO_D12),
    SD_PINCTRL_PIN(X9_PINCTRL_GPIO_D13),
    SD_PINCTRL_PIN(X9_PINCTRL_GPIO_D14),
    SD_PINCTRL_PIN(X9_PINCTRL_GPIO_D15),
	SD_PINCTRL_PIN(X9_PINCTRL_OSPI2_SCLK),
    SD_PINCTRL_PIN(X9_PINCTRL_OSPI2_SS0),
    SD_PINCTRL_PIN(X9_PINCTRL_OSPI2_DATA0),
    SD_PINCTRL_PIN(X9_PINCTRL_OSPI2_DATA1),
    SD_PINCTRL_PIN(X9_PINCTRL_OSPI2_DATA2),
    SD_PINCTRL_PIN(X9_PINCTRL_OSPI2_DATA3),
    SD_PINCTRL_PIN(X9_PINCTRL_OSPI2_DATA4),
    SD_PINCTRL_PIN(X9_PINCTRL_OSPI2_DATA5),
    SD_PINCTRL_PIN(X9_PINCTRL_OSPI2_DATA6),
    SD_PINCTRL_PIN(X9_PINCTRL_OSPI2_DATA7),
    SD_PINCTRL_PIN(X9_PINCTRL_OSPI2_DQS),
    SD_PINCTRL_PIN(X9_PINCTRL_OSPI2_SS1),
    SD_PINCTRL_PIN(X9_PINCTRL_RGMII2_TXC),
    SD_PINCTRL_PIN(X9_PINCTRL_RGMII2_TXD0),
    SD_PINCTRL_PIN(X9_PINCTRL_RGMII2_TXD1),
    SD_PINCTRL_PIN(X9_PINCTRL_RGMII2_TXD2),
    SD_PINCTRL_PIN(X9_PINCTRL_RGMII2_TXD3),
    SD_PINCTRL_PIN(X9_PINCTRL_RGMII2_TX_CTL),
    SD_PINCTRL_PIN(X9_PINCTRL_RGMII2_RXC),
    SD_PINCTRL_PIN(X9_PINCTRL_RGMII2_RXD0),
    SD_PINCTRL_PIN(X9_PINCTRL_RGMII2_RXD1),
    SD_PINCTRL_PIN(X9_PINCTRL_RGMII2_RXD2),
    SD_PINCTRL_PIN(X9_PINCTRL_RGMII2_RXD3),
    SD_PINCTRL_PIN(X9_PINCTRL_RGMII2_RX_CTL),
    SD_PINCTRL_PIN(X9_PINCTRL_I2S_SC3_SCK),
    SD_PINCTRL_PIN(X9_PINCTRL_I2S_SC3_WS),
    SD_PINCTRL_PIN(X9_PINCTRL_I2S_SC3_SD),
    SD_PINCTRL_PIN(X9_PINCTRL_I2S_SC4_SCK),
    SD_PINCTRL_PIN(X9_PINCTRL_I2S_SC4_WS),
    SD_PINCTRL_PIN(X9_PINCTRL_I2S_SC4_SD),
    SD_PINCTRL_PIN(X9_PINCTRL_I2S_SC5_SCK),
    SD_PINCTRL_PIN(X9_PINCTRL_I2S_SC5_WS),
    SD_PINCTRL_PIN(X9_PINCTRL_I2S_SC5_SD),
    SD_PINCTRL_PIN(X9_PINCTRL_I2S_SC6_SCK),
    SD_PINCTRL_PIN(X9_PINCTRL_I2S_SC6_WS),
    SD_PINCTRL_PIN(X9_PINCTRL_I2S_SC6_SD),
    SD_PINCTRL_PIN(X9_PINCTRL_I2S_SC7_SCK),
    SD_PINCTRL_PIN(X9_PINCTRL_I2S_SC7_WS),
    SD_PINCTRL_PIN(X9_PINCTRL_I2S_SC7_SD),
    SD_PINCTRL_PIN(X9_PINCTRL_I2S_SC8_SCK),
    SD_PINCTRL_PIN(X9_PINCTRL_I2S_SC8_WS),
    SD_PINCTRL_PIN(X9_PINCTRL_I2S_SC8_SD),
    SD_PINCTRL_PIN(X9_PINCTRL_I2S_MC_SCK),
    SD_PINCTRL_PIN(X9_PINCTRL_I2S_MC_WS),
    SD_PINCTRL_PIN(X9_PINCTRL_I2S_MC_SD0),
    SD_PINCTRL_PIN(X9_PINCTRL_I2S_MC_SD1),
    SD_PINCTRL_PIN(X9_PINCTRL_I2S_MC_SD2),
    SD_PINCTRL_PIN(X9_PINCTRL_I2S_MC_SD3),
    SD_PINCTRL_PIN(X9_PINCTRL_I2S_MC_SD4),
    SD_PINCTRL_PIN(X9_PINCTRL_I2S_MC_SD5),
    SD_PINCTRL_PIN(X9_PINCTRL_I2S_MC_SD6),
    SD_PINCTRL_PIN(X9_PINCTRL_I2S_MC_SD7),
    SD_PINCTRL_PIN(X9_PINCTRL_EMMC1_CLK),
    SD_PINCTRL_PIN(X9_PINCTRL_EMMC1_CMD),
    SD_PINCTRL_PIN(X9_PINCTRL_EMMC1_DATA0),
    SD_PINCTRL_PIN(X9_PINCTRL_EMMC1_DATA1),
    SD_PINCTRL_PIN(X9_PINCTRL_EMMC1_DATA2),
    SD_PINCTRL_PIN(X9_PINCTRL_EMMC1_DATA3),
    SD_PINCTRL_PIN(X9_PINCTRL_EMMC1_DATA4),
    SD_PINCTRL_PIN(X9_PINCTRL_EMMC1_DATA5),
    SD_PINCTRL_PIN(X9_PINCTRL_EMMC1_DATA6),
    SD_PINCTRL_PIN(X9_PINCTRL_EMMC1_DATA7),
    SD_PINCTRL_PIN(X9_PINCTRL_EMMC1_STROBE),
    SD_PINCTRL_PIN(X9_PINCTRL_EMMC1_RESET_N),
    SD_PINCTRL_PIN(X9_PINCTRL_EMMC2_CLK),
    SD_PINCTRL_PIN(X9_PINCTRL_EMMC2_CMD),
    SD_PINCTRL_PIN(X9_PINCTRL_EMMC2_DATA0),
    SD_PINCTRL_PIN(X9_PINCTRL_EMMC2_DATA1),
    SD_PINCTRL_PIN(X9_PINCTRL_EMMC2_DATA2),
    SD_PINCTRL_PIN(X9_PINCTRL_EMMC2_DATA3),
    SD_PINCTRL_PIN(X9_PINCTRL_EMMC2_DATA4),
    SD_PINCTRL_PIN(X9_PINCTRL_EMMC2_DATA5),
    SD_PINCTRL_PIN(X9_PINCTRL_EMMC2_DATA6),
    SD_PINCTRL_PIN(X9_PINCTRL_EMMC2_DATA7),
    SD_PINCTRL_PIN(X9_PINCTRL_EMMC2_STROBE),
    SD_PINCTRL_PIN(X9_PINCTRL_EMMC2_RESET_N),
};

static struct sd_pinctrl_soc_info kunlun_pinctrl_info = {
	.pins = kunlun_pinctrl_pads,
	.npins = ARRAY_SIZE(kunlun_pinctrl_pads),
};

static struct of_device_id kunlun_pinctrl_of_match[] = {
	{ .compatible = "semidrive,kunlun-pinctrl", },
	{ /* sentinel */ }
};

static int kunlun_pinctrl_probe(struct platform_device *pdev)
{

	return sd_pinctrl_probe(pdev, &kunlun_pinctrl_info);
}

static int kunlun_pinctrl_suspend(struct device *dev)
{

       return sd_pinctrl_suspend(dev);
}

static int kunlun_pinctrl_resume(struct device *dev)
{

       return sd_pinctrl_resume(dev);
}

static const struct dev_pm_ops kunlun_pinctrl_pm_ops = {
       SET_LATE_SYSTEM_SLEEP_PM_OPS(kunlun_pinctrl_suspend, kunlun_pinctrl_resume)
};

static struct platform_driver kunlun_pinctrl_driver = {
	.driver = {
		.name = "kunlun-pinctrl",
		.of_match_table = of_match_ptr(kunlun_pinctrl_of_match),
		.pm = &kunlun_pinctrl_pm_ops,
	},
	.probe = kunlun_pinctrl_probe,
};

static int __init kunlun_pinctrl_init(void)
{
	return platform_driver_register(&kunlun_pinctrl_driver);
}
arch_initcall(kunlun_pinctrl_init);
