# Semidrive ALSA SoC driver

snd-sdrv-i2s-sc-objs := sdrv-i2s-sc.o
obj-$(CONFIG_SND_SDRV_AFE_I2S_SC) += snd-sdrv-i2s-sc.o

snd-sdrv-i2s-mc-objs := sdrv-i2s-mc.o
obj-$(CONFIG_SND_SDRV_AFE_I2S_MC) += snd-sdrv-i2s-mc.o

snd-sdrv-spdif-objs := sdrv-spdif.o
obj-$(CONFIG_SND_SDRV_AFE_SPDIF) += snd-sdrv-spdif.o

snd-sdrv-remote-pcm-objs := sdrv-remote-pcm.o
obj-$(CONFIG_SND_SDRV_REMOTE_I2S) += snd-sdrv-remote-pcm.o

snd-sdrv-i2s-rpmsg-objs := sdrv-i2s-rpmsg.o
obj-$(CONFIG_SND_SDRV_I2S_USE_RPMSG) += sdrv-i2s-rpmsg.o

snd-sdrv-rpmsg-pcm-objs := sdrv-rpmsg-pcm.o
obj-$(CONFIG_SND_SDRV_I2S_USE_RPMSG) += sdrv-rpmsg-pcm.o

snd-sdrv-i2s-unilink-objs := sdrv-i2s-unilink.o
obj-$(CONFIG_SND_SDRV_I2S_USE_UNILINK) += sdrv-i2s-unilink.o

snd-sdrv-unilink-pcm-objs := sdrv-unilink-pcm.o
obj-$(CONFIG_SND_SDRV_I2S_USE_UNILINK) += sdrv-unilink-pcm.o

snd-x9-fpga-mach-objs := x9-fpga-mach.o
obj-$(CONFIG_SND_X9_FPGA_MACH) += snd-x9-fpga-mach.o

snd-x9-evb-mach-objs := x9-evb-mach.o
obj-$(CONFIG_SND_X9_EVB_MACH) += snd-x9-evb-mach.o

snd-x9-ref-mach-ak7738-objs := x9-ref-mach-ak7738.o
obj-$(CONFIG_SND_X9_REF_MACH_AK7738) += x9-ref-mach-ak7738.o

snd-x9-ref04-mach-ak7738-objs := x9-ref04-mach-ak7738.o
obj-$(CONFIG_SND_X9_REF04_MACH_AK7738) += x9-ref04-mach-ak7738.o

snd-x9-ref-mach-objs := x9-ref-mach.o
obj-$(CONFIG_SND_X9_REF_MACH) += x9-ref-mach.o

snd-x9-ref-mach-remote-objs := x9-ref-mach-remote.o
obj-$(CONFIG_SND_X9_REF_MACH_REMOTE) += x9-ref-mach-remote.o

snd-x9-icl02-mach-objs := x9-icl02-mach-ak7738.o
obj-$(CONFIG_SND_X9_ICL02_MACH) += x9-icl02-mach-ak7738.o

snd-x9-core01-mach-objs := x9-core01-mach-ak7738.o
obj-$(CONFIG_SND_X9_CORE01_MACH) += x9-core01-mach-ak7738.o

snd-x9-ref-mach-ak4556-objs := x9-ref-mach-ak4556.o
obj-$(CONFIG_SND_X9_REF_MACH_HS) += x9-ref-mach-ak4556.o

snd-x9-ref-mach-tlv320aic23-objs := x9-ref-mach-tlv320aic23.o
obj-$(CONFIG_SND_X9_REF_MACH_TLV320AIC23) += x9-ref-mach-tlv320aic23.o

snd-x9u-msb1-mach-tlv320aic23-objs := x9u-msb1-mach-tlv320aic23.o
obj-$(CONFIG_SND_X9_MSB1_MACH_TLV320AIC23) += x9u-msb1-mach-tlv320aic23.o

snd-g9-ref-mach-objs := g9-ref-mach.o
obj-$(CONFIG_SND_G9_REF_MACH) += snd-g9-ref-mach.o

snd-g9-ref-mach-tlv320aic23-objs := g9-ref-mach-tlv320aic23.o
obj-$(CONFIG_SND_G9_REF_MACH_TLV320AIC23) += g9-ref-mach-tlv320aic23.o

snd-d9-ref-mach-es7243e-objs := d9-ref-mach-es7243e.o
obj-$(CONFIG_SND_D9_REF_MACH_ES7243E) += snd-d9-ref-mach-es7243e.o

snd-d9-ref-mach-es7144-objs := d9-ref-mach-es7144.o
obj-$(CONFIG_SND_D9_REF_MACH_ES7144) += snd-d9-ref-mach-es7144.o

obj-$(CONFIG_SEMIDRIVE_AUDIO_SERVICE) += audio_service/

snd-x9-ms-mach-objs := x9-ms-mach.o
obj-$(CONFIG_SND_X9_MS_MACH) += x9-ms-mach.o